# Implimenting Forward propagation and back propagation for NN with hidden layer

## Implimenting XOR function

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
Y.shape

(4, 1)

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
# One hidden layer : Weights from 2 input neuron to 2 hidden neuron
wH = 2*np.random.random((2,2))-1
bH = 2*np.random.random((1,2))-1

In [6]:
# Output Layer weights : from 2 hidden neurons to 1 output neuron
wO = 2*np.random.random((2,1))-1
bO = 2*np.random.random((1))-1
lr = 0.1
wO.shape

(2, 1)

In [111]:
# Implimenting forward propagation with oneHidden layer
for iter in range(10000):
    output_InputLayer = X
    input_HiddenLayer = np.dot(output_InputLayer,wH)+bH
    output_HiddenLayer = sig(input_HiddenLayer)
    input_OutputLayer = np.dot(output_HiddenLayer,wO)+bO 
    output = sig(input_OutputLayer)
    # print(output.shape)


    # Implimentation of backPropagtion of this NN
    ## FirstTwo terms for outputLayer
    firstTerm_OutputLayer = output - Y
    secondTerm_OutputLayer = derivativeSig(input_OutputLayer)
    firstTwo_OutputLayer = firstTerm_OutputLayer * secondTerm_OutputLayer

    ## So now we would backpropagate the firstTwo terms from outputLayer to hiddenLayer
    firstTerm_HiddenLayer = np.dot(firstTwo_OutputLayer, wO.T)
    secondTerm_HiddenLayer = derivativeSig(input_HiddenLayer)
    firstTwo_HiddenLayer = firstTerm_HiddenLayer*secondTerm_HiddenLayer

    ## To find the changesWeights netween outputLayer and hidden layer, the dot prdt of firstTwo of outputLayer with output of hidden layer 
    changes_Output_Hidden = np.dot(output_HiddenLayer.T, firstTwo_OutputLayer)
    changes_Output_Hidden_Bias = np.sum(firstTwo_OutputLayer,axis=0,keepdims = True)
    ### The {keepdims} would do that after the summation we should not get the dimnesionless value(scaler) it would let the "sum" same dimension as of its parent so that vecot addition works fine 
    ### The axis = 0, summation would done by adding each row in the col , in 1 changes by column

    ## Same above concept for the weightsChanges between hidden and input
    changes_Hidden_input = np.dot(output_InputLayer.T, firstTwo_HiddenLayer)
    changes_Hidden_input_Bias = np.sum(firstTwo_HiddenLayer,axis=0,keepdims = True) ### Same concept added as above 

    ## Now updation of the paramerts
    wO = wO - lr * changes_Output_Hidden
    bO = bO - lr * changes_Output_Hidden_Bias

    wH = wH - lr * changes_Hidden_input
    bH = bH - lr * changes_Hidden_input_Bias

output_InputLayer = X
input_HiddenLayer = np.dot(output_InputLayer,wH)+bH
output_HiddenLayer = sig(input_HiddenLayer)
input_OutputLayer = np.dot(output_HiddenLayer,wO)+bO 
output = sig(input_OutputLayer)
print(output)
print(wH,bH)
print(wO,bO)

[[0.02391121]
 [0.97908542]
 [0.97909868]
 [0.02498912]]
[[ 7.05047533 -5.37056001]
 [ 7.03956789 -5.36825797]] [[-3.16636353  8.04352205]]
[[8.64629365]
 [8.81134531]] [[-12.86747661]]


In [109]:
## So now we would backpropagate the firstTwo terms from outputLayer to hiddenLayer
# firstTerm_OutputLayer = output - Y
# secondTerm_OutputLayer = derivativeSig(input_OutputLayer)
# firstTwo_OutputLayer = firstTerm_OutputLayer * secondTerm_OutputLayer

# output_InputLayer = X
# input_HiddenLayer = np.dot(output_InputLayer,wH)+bH
# output_HiddenLayer = sig(input_HiddenLayer)
# input_OutputLayer = np.dot(output_HiddenLayer,wO)+bO 
# output = sig(input_OutputLayer)
    
firstTwo_HiddenLayer.shape

(4, 2)