# Forward Propagation with having no Hidden Layer, direct input layer and output layer

In [4]:
# Importing library
import numpy as np

In [5]:
# $ possible values as our input as AND operator
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,0,0,1])

In [9]:
print(X)
print(Y)
Y.reshape(-1,1) # converted into 2D array(Matrix formate) as same as our X 

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 0 0 1]


array([[0],
       [0],
       [0],
       [1]])

## Defining Sigmid function

In [59]:
# Defining the sigmoid function:
def sig(z):
    return (1/(1+np.exp(-z))) 

## Defining the weights as per following the rules, no hidden layer weights, that is from input neuron to direct output neuron

In [74]:
# Intilize random weights to start with forward propagation
# From np.random module, a random function is there, which provides random number as given the shape parametrs, so we required 2 rows and 1 column, as from 2-input-neuron to 1-output-neuron -> (2,1)
weights = 2*np.random.random((2,1))-1 #But it would give numbers in range of 0 to 1 , but we required -1 to 1, so we first multiply it with 2, so that range became 0 to 2, and then substracted by 1 so that range became -1 to 1
print(weights.shape)
weights # As we reuired ideal weights to be from -1 to 1 and should be in 2D. as co be equal to 1 

(2, 1)


array([[ 0.64724472],
       [-0.60338515]])

## Defining the bias, as we required here only 1 bias, that is from inptu neuron to direct output neuron

In [61]:
bias = 2 * np.random.random(1)-1 # Same concept as implimneted above, same -1 to 1
# Shape inside passed (1), bias is bydefault 1, so bias connected to how many neuron passed here that is (1) 
bias

array([0.66699023])

## Constructing the network for forward propagation without any hidden layer

In [73]:
## Now input layer output is directly giving the output
inputOut = X
output = sig(np.dot(inputOut, weights)+ bias) #Vector multiplication / matrix multiplication of X and weights, 4x2 into 2x1 would give 4x1 and there summation with eachother as well as with bias will be passed to sigmoid function which gonna be our output 
# Here np.dot will multiply first datapoint with weights and summed summed with eachohter as well with bias also and call sigmoid function and return value to output same with next datapoints in X(inputOut), and saved them all in output which is a array/list 
print(type(output))
output

<class 'numpy.ndarray'>


array([[0.66082889],
       [0.61835401],
       [0.54797069],
       [0.50201305]])