# ForwardPropagation on neural net which has also hidden layer with intput and output layer

In [6]:
# IMporting libraries
import numpy as np

In [7]:
# Creating our own input and outpput datasets (AND)
X = np.array([[0,0],[0,1],[1,0],[1,1]]) 
Y = np.array([[0,0,0,1]]).reshape(-1,1) # reshaped it to 2D array or matrix just like X 
print(X)
Y

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


array([[0],
       [0],
       [0],
       [1]])

## Defining sigmoid function

In [8]:
def sig(z):
    return (1/(1+np.exp(-z)))

## Defining Weights as per having one hidden layer, that is from input neuron to hideen neuron

In [22]:
# Intilize random weights to start with forward propagation
# From np.random module, a random function is there, which provides random number as given the shape parametrs, so we required 2 rows and 2 column, as from 2-input-neuron to 2-hidden-neuron -> (2,2)
weights_hidden = 2*np.random.random((2,2))-1 #But it would give numbers in range of 0 to 1 , but we required -1 to 1, so we first multiply it with 2, so that range became 0 to 2, and then substracted by 1 so that range became -1 to 1 
print(weights_hidden.shape)
weights_hidden # As we reuired ideal weights to be from -1 to 1 and should be in 2D. as co be equal to 1 

(2, 2)


array([[ 0.41435992, -0.8167367 ],
       [ 0.25580858, -0.15167325]])

## Defining the bias as per having one hidden layer, that is from input neuron to hidden neuron

In [41]:
# Defining the biases
bias_hidden = 2*np.random.random(2)-1
bias_hidden

array([-0.85530597,  0.19168994])

## Now defining the weights and biases from hiddden layer to output layer

In [53]:
# Intilize random weights to start with forward propagation
# From np.random module, a random function is there, which provides random number as given the shape parametrs, so we required 2 rows and 2 column, as from 2-input-neuron to 2-hidden-neuron -> (2,2)
weights_output = 2*np.random.random((2,1))-1 #But it would give numbers in range of 0 to 1 , but we required -1 to 1, so we first multiply it with 2, so that range became 0 to 2, and then substracted by 1 so that range became -1 to 1 
print(weights_output.shape)
weights_output # As we reuired ideal weights to be from -1 to 1 and should be in 2D. as co be equal to 1 

(2, 1)


array([[ 0.97957961],
       [-0.64007166]])

In [57]:
# Defining the biases
bias_output = 2*np.random.random(1)-1
bias_output

array([0.64968683])

## Construction of Neural netowrk and impliemntation of it

In [58]:
# Implimentation of first connection of NN, that input_layer -> hidden_layer
inputHidden = X
outputHidden = sig(np.dot(inputHidden, weights_hidden)+bias_hidden)
outputHidden

array([[0.70486173, 0.38938597],
       [0.75516769, 0.35398522],
       [0.7832857 , 0.21983457],
       [0.82357027, 0.19492761]])

In [59]:
# Implimnetation of second connection of NN, that is hidden_layer->output_layer
output = sig(np.dot(outputHidden, weights_output)+bias_output)
output

array([[0.74855494],
       [0.7618516 ],
       [0.78181378],
       [0.79111704]])