# Implimnetation of Backpropagation in NN having no hidden layer, just input layer and hidden layer

## (*)First writing forwar prop code, as at starting random weights are assumed and forward propagate and when get y_pred, then calculate error and backpropagate , from gradient descent to get optimum value of weights


In [241]:
# Importing libraies
import numpy as np

In [242]:
# Arraning our inputs and output
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]])
Y = Y.T
print(X.shape)
print(Y.shape)

(4, 2)
(4, 1)


In [243]:
# Defining sigmoid function
def sig(z):
    return 1/(1+np.exp(-z))

In [244]:
# Defining derivative of sigmoid
def derivativeSig(z):
    return sig(z)*(1-sig(z))

## Defining weights and biases for no hidden layer NN

In [245]:
# Randomly declaring them in range from -1 to 1
weights = 2*np.random.random((2,1)) - 1 
biase = 2*np.random.random(1)-1
weights , biase

(array([[0.56567058],
        [0.45273601]]),
 array([-0.95462463]))

In [246]:
# Defining the connection between input to output and finding prediction
outputInputLayer = X
output = sig(np.dot(outputInputLayer,weights) + biase)
print(output)

[[0.27795572]
 [0.37709694]
 [0.40396912]
 [0.51594009]]


## Above was for the forwardPropagation

## Now towards backward propagation,
### *) We would do forward prop once then change the derivative we have, then again same , similarly like we do it in gradient descent multiple time in the form of iterations

In [247]:
# Calculating first term og the derivative
firstTerm = output - Y
firstTerm

array([[ 0.27795572],
       [ 0.37709694],
       [ 0.40396912],
       [-0.48405991]])

In [248]:
# Calculating the secondTerm of the derivative
Oj = output
secondTerm = derivativeSig(Oj)
secondTerm

array([[0.24523279],
       [0.24131884],
       [0.24007169],
       [0.23407408]])

In [249]:
# Now lets calculate the product of first-two term
firstTwo = firstTerm * secondTerm
print(firstTwo.shape)
firstTwo

(4, 1)


array([[ 0.06816386],
       [ 0.0910006 ],
       [ 0.09698155],
       [-0.11330588]])

In [250]:
lr = 0.00000000001 # Defined learningRate

## Lets multiply the firstTwo with third which is input matrix, for respective columns represent respective weights


In [251]:
# Lets get the altered separte matrix for each weight
changes = np.array([[0.0],[0.0]]) # Variable saving weightMatrix same dimnesion (2,1) and then saved to real weightMatrix variable above   

for i in range (2):
    for j in range(4):
        changes[i][0] += firstTwo[j][0] * X[j][i]
print(changes)# Containing new altered weights retrived from the derivative of error function wrt weights 
print()
# Updating the weights from the new ones
weights = weights - lr * changes
print(weights)

[[-0.01632433]
 [-0.02230528]]

[[0.56567058]
 [0.45273601]]


## Lets do same for the new altered biase

In [252]:
# Everything would be same as its also caontaining weights, one thing different that is value of the Inputneuron is 1 
changes_biase = np.array([0.0])

for j in range(4):
    changes_biase[0] += firstTwo[j][0] * 1
    
print(changes_biase)
biase =biase - lr * changes_biase
biase

[0.14284012]


array([-0.95462463])

## Now lets run forward and back propagation for many times to reach to global minima

In [253]:
for iter in range(10000):
    output = sig(np.dot(X,weights)+biase)
    first = output - Y
    second = derivativeSig(output)
    firstTwo = first * second
    
    weightsNew = np.array([[0.0],[0.0]])
    biaseNew = 0.0
    
    for i in range(2):
        for j in range(4):
            weightsNew += firstTwo[j][0] * X[j][i] 
    weights = weights - lr*weightsNew
    
    for i in range(4):
        biaseNew += firstTwo[j][0] * 1
    biase = biase - lr*biaseNew
    
output = sig(np.dot(X,weights)+biase)
print(output)
print(weights)
biase

[[0.27795573]
 [0.37709695]
 [0.40396913]
 [0.5159401 ]]
[[0.56567058]
 [0.45273602]]


array([-0.95462458])